# Generated by Django 4.1.5 on 2023-02-15 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['-id'], 'verbose_name': 'менеджер', 'verbose_name_plural': 'менеджер'},
        ),
        migrations.AddField(
            model_name='user',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Тіркелген уақыты'),
            preserve_default=False,
        ),
    ]
