# Generated by Django 4.1.5 on 2023-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0002_alter_manager_options_user_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Date_end',
            field=models.DateTimeField(verbose_name='Қайтару уақыты'),
        ),
    ]
