# Generated by Django 4.1.5 on 2023-02-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0003_alter_manager_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Тапсырды'),
        ),
    ]
