# Generated by Django 4.1.5 on 2023-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0004_manager_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='age',
            field=models.IntegerField(default=2023, verbose_name='Нешінші жылғы кітап'),
        ),
    ]
