# Generated by Django 4.1.5 on 2023-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0005_alter_books_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кітап саны'),
        ),
    ]
