# Generated by Django 4.1.5 on 2023-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0006_books_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Жаңалық аты')),
                ('image', models.ImageField(upload_to='', verbose_name='Жаңалық фотосы')),
                ('descriptionNews', models.TextField(verbose_name='Жаңалық сипаттамасы')),
            ],
            options={
                'verbose_name': 'жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-id'],
            },
        ),
    ]
